# SPDX-FileCopyrightText: Allen Winter <winter@kde.org>
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "KOrganizer"
SPDX-PackageDownloadLocation = "https://invent.kde.org/pim/korganizer"

[[annotations]]
path = ["README-pre-commit.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023-2025 Laurent Montel <montel@kde.org>"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = ["CMakePresets.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2021 Laurent Montel <montel@kde.org>"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = ["README.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2020 Allen Winter <winter@kde.org>"
SPDX-License-Identifier = "CC0-1.0"
